# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Di heng/Desktop/SCSE Y2S2/SC2103 Digital Systems Design/Lab/Lab 2/project_1/project_1.srcs/sources_1/ip/Lab2_mem/Lab2_mem.xci
# IP: The module: 'Lab2_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Di heng/Desktop/SCSE Y2S2/SC2103 Digital Systems Design/Lab/Lab 2/project_1/project_1.gen/sources_1/ip/Lab2_mem/Lab2_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Di heng/Desktop/SCSE Y2S2/SC2103 Digital Systems Design/Lab/Lab 2/project_1/project_1.srcs/sources_1/ip/Lab2_mem/Lab2_mem.xci
# IP: The module: 'Lab2_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Di heng/Desktop/SCSE Y2S2/SC2103 Digital Systems Design/Lab/Lab 2/project_1/project_1.gen/sources_1/ip/Lab2_mem/Lab2_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
